name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Only test on macOS 14 (ARM64) since XCFrameworks only contain ARM64 binaries
        os: [macos-14]
        xcode: ['15.2']
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
    - name: Show Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

  swift-package-validation:
    name: Swift Package Validation
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Validate Swift Package
      run: |
        # Test that the package can be resolved
        swift package resolve
        
        # Show package dependencies
        swift package show-dependencies
        
        # TODO: Enable iOS builds once iOS libraries are added to XCFrameworks
        # Currently XCFrameworks only contain macOS libraries
        # xcodebuild -scheme TesseractSwift -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' build
        
        # Verify package builds for macOS
        xcodebuild -scheme TesseractSwift -destination 'platform=macOS' build

  lint:
    name: SwiftLint
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint --strict

  documentation:
    name: Documentation Build
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Build Documentation
      run: |
        swift package generate-documentation
      continue-on-error: true # DocC might not be fully configured yet