name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Build and Test
      run: |
        swift build -v
        swift test -v
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - See [CHANGELOG.md](https://github.com/amebalabs/TesseractSwift/blob/main/CHANGELOG.md) for details
        draft: false
        prerelease: false

  validate-spm:
    name: Validate Swift Package
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Package
      run: |
        swift package resolve
        swift build -c release
        
    - name: Archive XCFrameworks
      run: |
        zip -r TesseractCore.xcframework.zip Sources/XCFrameworks/TesseractCore.xcframework
        zip -r Leptonica.xcframework.zip Sources/XCFrameworks/Leptonica.xcframework
        
    - name: Upload XCFrameworks
      uses: actions/upload-artifact@v3
      with:
        name: xcframeworks
        path: |
          TesseractCore.xcframework.zip
          Leptonica.xcframework.zip